### ISSUE TITLE
com.apple.desktoppicture目录问题

### ISSUE THREAD

**Issue by veapon** [xiqishow/bing_wallpaper#3]
MacOS好像会另外保存一份壁纸文件，用了一段时间后，发现 /private/var/folders/jv/51w75rcx4dl8b2h6drj2zvj40000gn/C/com.apple.desktoppicture (因人而异)磁盘占用会很恐怖，如下图，目前我的解决方案是在wallpaper.sh执行的时候清一下这个目录
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1680913/166951959-a88a3ae8-916f-4807-84a9-294cb4aa5b59.png">

**Comment by xiqishow** [comment]
嗯 发现了这个问题 可是这个目录是macos自身系统文件夹 并且每台mac的目录也不尽相同，只能自己去删除一下了，在脚本添加删除的过程，默认脚本本身没有权限去改动系统文件夹

**Comment by xiqishow** [comment]
看新版的MacOS已经自动清理掉这些文件了

**Comment by fantasyado** [comment]
遇到了一样的问题。。我的占用了200多G,用Lemon磁盘分析才扫出来
